#!/bin/bash

SRC_DIR=/media/vendor/app
TRG_DIR=/data/android_vendor_google/flame/proprietary/app
cp --no-preserve=mode,ownership $SRC_DIR/CACertService/CACertService.apk $TRG_DIR/CACertService/
cp --no-preserve=mode,ownership $SRC_DIR/CneApp/CneApp.apk $TRG_DIR/CneApp/
cp --no-preserve=mode,ownership $SRC_DIR/IWlanService/IWlanService.apk $TRG_DIR/IWlanService/

SRC_DIR=/media/system/bin/
TRG_DIR=/data/android_vendor_google/flame/proprietary/bin
cp --no-preserve=mode,ownership $SRC_DIR/iw $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/move_time_data.sh $TRG_DIR/

SRC_DIR=/media/system/etc/permissions
TRG_DIR=/data/android_vendor_google/flame/proprietary/etc/permissions
cp --no-preserve=mode,ownership $SRC_DIR/com.qti.snapdragon.sdk.display.xml $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/privapp-permissions-google.xml $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/privapp-permissions-platform.xml $TRG_DIR/

SRC_DIR=/media/system/framework
TRG_DIR=/data/android_vendor_google/flame/proprietary/framework
cp --no-preserve=mode,ownership $SRC_DIR/com.qti.snapdragon.sdk.display.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.uceservice-V2.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.alarm-V1.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.latency-V1.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.factory-V1.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.ims.callinfo-V1.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.voiceprint-V1.0-java.jar $TRG_DIR/

SRC_DIR=/media/system/lib
TRG_DIR=/data/android_vendor_google/flame/proprietary/lib
cp --no-preserve=mode,ownership $SRC_DIR/android.hardware.radio@1.3.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/android.hardware.radio@1.4.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.bluetooth_audio@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.uceservice@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libadsprpc_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libcdsprpc_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdiag_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdisplayconfig.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/liblogwrap.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libmdsprpc_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libminui.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libmmosal.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libnl.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libOpenCL_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libprotobuf-cpp-full.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmi_cci_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsdsprpc_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvr_amb_engine.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvraudio_client.qti.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvraudio.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvr_object_engine.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvr_sam_wrapper.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.2.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.3.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.4.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.5.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.6.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.postproc@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.alarm@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.latency@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.factory@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.iop@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.iop@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.perf@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.qteeconnector@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.am@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.2.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.3.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.4.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qcrilhook@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qtiradio@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qtiradio@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim_remote_client@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim_remote_server@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.seccam@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.tui_comm@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.ims.callinfo@1.0.so $TRG_DIR/

SRC_DIR=/media/vendor/lib
TRG_DIR=/data/android_vendor_google/flame/proprietary/lib
cp --no-preserve=mode,ownership $SRC_DIR/libcacertclient.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdiag.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdsutils.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libidl.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libjnihelper.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libmdmdetect.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmi_cci.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmi_client_qmux.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmi_encdec.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmiservices.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.cacert@1.0.so $TRG_DIR/

SRC_DIR=/media/system/lib64
TRG_DIR=/data/android_vendor_google/flame/proprietary/lib64
cp --no-preserve=mode,ownership $SRC_DIR/android.hardware.radio@1.3.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/android.hardware.radio@1.4.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.bluetooth_audio@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.uceservice@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libadsprpc_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libcdsprpc_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdiag_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdisplayconfig.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libmdsprpc_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libminui.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libmmosal.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libnl.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libOpenCL_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libprotobuf-cpp-full.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmi_cci_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsdsprpc_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvr_amb_engine.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvraudio_client.qti.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvraudio.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvr_object_engine.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libvr_sam_wrapper.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.color@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.2.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.3.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.4.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.5.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.config@1.6.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.display.postproc@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.alarm@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.latency@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.factory@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.iop@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.iop@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.perf@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.qteeconnector@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.am@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.2.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.3.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.ims@1.4.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qcrilhook@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qtiradio@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qtiradio@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim_remote_client@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim_remote_server@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.seccam@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.tui_comm@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.ims.callinfo@1.0.so $TRG_DIR/

SRC_DIR=/media/vendor/lib64
TRG_DIR=/data/android_vendor_google/flame/proprietary/lib64
cp --no-preserve=mode,ownership $SRC_DIR/libcacertclient.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdiag.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdsutils.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libidl.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libjnihelper.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libmdmdetect.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmi_cci.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmi_client_qmux.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmi_encdec.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libqmiservices.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.cacert@1.0.so $TRG_DIR/


SRC_DIR=/media/product/app
TRG_DIR=/data/android_vendor_google/flame/proprietary/product/app
cp --no-preserve=mode,ownership $SRC_DIR/atfwd/atfwd.apk $TRG_DIR/atfwd/
cp --no-preserve=mode,ownership $SRC_DIR/colorservice/colorservice.apk $TRG_DIR/colorservice/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.services.secureui/com.qualcomm.qti.services.secureui.apk $TRG_DIR/com.qualcomm.qti.services.secureui/
cp --no-preserve=mode,ownership $SRC_DIR/datastatusnotification/datastatusnotification.apk $TRG_DIR/datastatusnotification/
cp --no-preserve=mode,ownership $SRC_DIR/MotionSenseBridgePrebuilt/MotionSenseBridgePrebuilt.apk $TRG_DIR/MotionSenseBridgePrebuilt/
cp --no-preserve=mode,ownership $SRC_DIR/QdcmFF/QdcmFF.apk $TRG_DIR/QdcmFF/
cp --no-preserve=mode,ownership $SRC_DIR/QtiTelephonyService/QtiTelephonyService.apk $TRG_DIR/QtiTelephonyService/
cp --no-preserve=mode,ownership $SRC_DIR/SSRestartDetector/SSRestartDetector.apk $TRG_DIR/SSRestartDetector/
cp --no-preserve=mode,ownership $SRC_DIR/Tycho/Tycho.apk $TRG_DIR/Tycho/
cp --no-preserve=mode,ownership $SRC_DIR/uceShimService/uceShimService.apk $TRG_DIR/uceShimService/
cp --no-preserve=mode,ownership $SRC_DIR/uimremoteclient/uimremoteclient.apk $TRG_DIR/uimremoteclient/
cp --no-preserve=mode,ownership $SRC_DIR/uimremoteserver/uimremoteserver.apk $TRG_DIR/uimremoteserver/
cp --no-preserve=mode,ownership $SRC_DIR/VZWAPNLib/VZWAPNLib.apk $TRG_DIR/VZWAPNLib/

SRC_DIR=/media/product/etc
TRG_DIR=/data/android_vendor_google/flame/proprietary/product/etc
rm -f $TRG_DIR/CarrierSettings/*
cp --no-preserve=mode,ownership $SRC_DIR/CarrierSettings/* $TRG_DIR/CarrierSettings/

cp --no-preserve=mode,ownership $SRC_DIR/ambient/matcher_tah.leveldb $TRG_DIR/ambient/

cp --no-preserve=mode,ownership $SRC_DIR/felica/common.cfg $TRG_DIR/felica/
cp --no-preserve=mode,ownership $SRC_DIR/felica/mfm.cfg $TRG_DIR/felica/
cp --no-preserve=mode,ownership $SRC_DIR/felica/mfs.cfg $TRG_DIR/felica/

cp --no-preserve=mode,ownership $SRC_DIR/firmware/music_detector.descriptor $TRG_DIR/firmware/
cp --no-preserve=mode,ownership $SRC_DIR/firmware/music_detector.sound_model $TRG_DIR/firmware/

cp --no-preserve=mode,ownership $SRC_DIR/permissions/android.hardware.telephony.euicc.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.android.omadm.service.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.android.sdm.plugins.connmo.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.android.sdm.plugins.dcmo.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.android.sdm.plugins.diagmon.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.android.sdm.plugins.sprintdm.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.android.sdm.plugins.usccdm.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.android.vzwomatrigger.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.customermobile.preload.vzw.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.google.android.apps.dreamliner.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.google.android.hardwareinfo.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.google.omadm.trigger.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.qualcomm.qcrilmsgtunnel.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.verizon.apn.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.verizon.llkagent.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/com.verizon.services.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/features-verizon.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/obdm_permissions.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/org_codeaurora_ims.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/privapp-permissions-google-ps.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/privapp-permissions-google-p.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/qcrilhook.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/split-permissions-google.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/telephonyservice.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/tmo_grsu_permissions.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/uimremoteclient.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/uimremoteserver.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/UimService.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml $TRG_DIR/permissions/
cp --no-preserve=mode,ownership $SRC_DIR/permissions/vzw_mvs_permissions.xml $TRG_DIR/permissions/
sed -i 's/version="2.0"/version="1.0"/' $TRG_DIR/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml

cp --no-preserve=mode,ownership $SRC_DIR/res/images/charger/battery_fail.png $TRG_DIR/res/images/charger/
cp --no-preserve=mode,ownership $SRC_DIR/res/images/charger/battery_scale.png $TRG_DIR/res/images/charger/
cp --no-preserve=mode,ownership $SRC_DIR/res/images/charger/main_font.png $TRG_DIR/res/images/charger/
cp --no-preserve=mode,ownership $SRC_DIR/res/values/charger/animation.txt $TRG_DIR/res/values/charger/

cp --no-preserve=mode,ownership $SRC_DIR/sysconfig/dreamliner.xml $TRG_DIR/sysconfig/
cp --no-preserve=mode,ownership $SRC_DIR/sysconfig/nga.xml $TRG_DIR/sysconfig/
cp --no-preserve=mode,ownership $SRC_DIR/sysconfig/pixel_2019_exclusive.xml $TRG_DIR/sysconfig/
cp --no-preserve=mode,ownership $SRC_DIR/sysconfig/pixel_experience_2019_midyear.xml $TRG_DIR/sysconfig/
cp --no-preserve=mode,ownership $SRC_DIR/sysconfig/pixel_experience_2019.xml $TRG_DIR/sysconfig/
cp --no-preserve=mode,ownership $SRC_DIR/sysconfig/tmo_grsu_sysconfig.xml $TRG_DIR/sysconfig/
cp --no-preserve=mode,ownership $SRC_DIR/sysconfig/whitelist_com.android.omadm.service.xml $TRG_DIR/sysconfig/

cp --no-preserve=mode,ownership $SRC_DIR/vintf/manifest/vendor.qti.hardware.radio.atcmdfwd@1.0.xml $TRG_DIR/vintf/manifest/

SRC_DIR=/media/product/framework
TRG_DIR=/data/android_vendor_google/flame/proprietary/product/framework
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice-V2.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice-V2.1-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice-V2.2-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.uceservice-V2.1-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libhwinfo.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/qcrilhook.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/QtiTelephonyServicelibrary.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/uimremoteclientlibrary.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/uimremoteserverlibrary.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.connection-V1.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.dynamicdds-V1.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.iwlan-V1.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.ims.rcsconfig-V1.0-java.jar $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.latency-V2.0-java.jar $TRG_DIR/

SRC_DIR=/media/product/lib
TRG_DIR=/data/android_vendor_google/flame/proprietary/product/lib
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.ant@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice@2.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice@2.2.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.uceservice@2.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.api@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.api@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.constants@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.constants@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.constants@2.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdmengine.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdmjavaplugin.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libimscamera_jni.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libimsmedia_jni.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/lib-imsvideocodec.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/lib-imsvtextutils.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/lib-imsvt.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/lib-imsvtutils.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsdm-disp-apis.qti.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsd_sdk_display.qti.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsecureuisvc_jni.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsecureui_svcsock_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.google.wifi_ext@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.google.wireless_charger@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.google.wireless_charger@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.data.factory@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.connection@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.dynamicdds@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.iwlan@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.perf@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qtiradio@2.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qtiradio@2.2.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim_remote_client@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.ims.rcsconfig@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.imsrtpservice@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.latency@2.0.so $TRG_DIR/

SRC_DIR=/media/product/lib64
TRG_DIR=/data/android_vendor_google/flame/proprietary/product/lib64
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.ant@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice@2.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.imscmservice@2.2.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.qualcomm.qti.uceservice@2.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.api@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.api@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.constants@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.constants@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/com.quicinc.cne.constants@2.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libaptX_encoder.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libaptXHD_encoder.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libgdx.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libimscamera_jni.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libimsmedia_jni.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/lib-imsvideocodec.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/lib-imsvtextutils.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/lib-imsvt.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/lib-imsvtutils.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsdm-disp-apis.qti.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsd_sdk_display.qti.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsecureuisvc_jni.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libsecureui_svcsock_system.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.google.wifi_ext@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.google.wireless_charger@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.google.wireless_charger@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.data.factory@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.connection@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.dynamicdds@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.data.iwlan@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.perf@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qtiradio@2.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.qtiradio@2.2.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.hardware.radio.uim_remote_client@1.1.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.ims.rcsconfig@1.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.imsrtpservice@2.0.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/vendor.qti.latency@2.0.so $TRG_DIR/

SRC_DIR=/media/product/priv-app
TRG_DIR=/data/android_vendor_google/flame/proprietary/product/priv-app
cp --no-preserve=mode,ownership $SRC_DIR/AmbientSensePrebuilt/AmbientSensePrebuilt.apk $TRG_DIR/AmbientSensePrebuilt/
cp --no-preserve=mode,ownership $SRC_DIR/AppDirectedSMSService/AppDirectedSMSService.apk $TRG_DIR/AppDirectedSMSService/
cp --no-preserve=mode,ownership $SRC_DIR/CarrierLocation/CarrierLocation.apk $TRG_DIR/CarrierLocation/
cp --no-preserve=mode,ownership $SRC_DIR/CarrierServices/CarrierServices.apk $TRG_DIR/CarrierServices/
cp --no-preserve=mode,ownership $SRC_DIR/CarrierSettings/CarrierSettings.apk $TRG_DIR/CarrierSettings/
cp --no-preserve=mode,ownership $SRC_DIR/CarrierSetup/CarrierSetup.apk $TRG_DIR/CarrierSetup/
cp --no-preserve=mode,ownership $SRC_DIR/CarrierWifi/CarrierWifi.apk $TRG_DIR/CarrierWifi/
cp --no-preserve=mode,ownership $SRC_DIR/CbrsNetworkMonitor/CbrsNetworkMonitor.apk $TRG_DIR/CbrsNetworkMonitor/
cp --no-preserve=mode,ownership $SRC_DIR/ConnMO/ConnMO.apk $TRG_DIR/ConnMO/
cp --no-preserve=mode,ownership $SRC_DIR/DCMO/DCMO.apk $TRG_DIR/DCMO/
cp --no-preserve=mode,ownership $SRC_DIR/DiagMon/DiagMon.apk $TRG_DIR/DiagMon/
cp --no-preserve=mode,ownership $SRC_DIR/DMService/DMService.apk $TRG_DIR/DMService/
cp --no-preserve=mode,ownership $SRC_DIR/DreamlinerPrebuilt/DreamlinerPrebuilt.apk $TRG_DIR/DreamlinerPrebuilt/
cp --no-preserve=mode,ownership $SRC_DIR/DreamlinerUpdater/DreamlinerUpdater.apk $TRG_DIR/DreamlinerUpdater/
cp --no-preserve=mode,ownership $SRC_DIR/EuiccGoogle/EuiccGoogle.apk $TRG_DIR/EuiccGoogle/
cp --no-preserve=mode,ownership $SRC_DIR/EuiccSupportPixel/EuiccSupportPixel.apk $TRG_DIR/EuiccSupportPixel/
cp --no-preserve=mode,ownership $SRC_DIR/GCS/GCS.apk $TRG_DIR/GCS/
cp --no-preserve=mode,ownership $SRC_DIR/grilservice/grilservice.apk $TRG_DIR/grilservice/
cp --no-preserve=mode,ownership $SRC_DIR/HardwareInfo/HardwareInfo.apk $TRG_DIR/HardwareInfo/
cp --no-preserve=mode,ownership $SRC_DIR/HotwordEnrollmentOKGoogleHEMIDELTA/HotwordEnrollmentOKGoogleHEMIDELTA.apk $TRG_DIR/HotwordEnrollmentOKGoogleHEMIDELTA/
cp --no-preserve=mode,ownership $SRC_DIR/HotwordEnrollmentXGoogleHEMIDELTA/HotwordEnrollmentXGoogleHEMIDELTA.apk $TRG_DIR/HotwordEnrollmentXGoogleHEMIDELTA/
cp --no-preserve=mode,ownership $SRC_DIR/ims/ims.apk $TRG_DIR/ims/
cp --no-preserve=mode,ownership $SRC_DIR/LLKAgent/LLKAgent.apk $TRG_DIR/LLKAgent/
cp --no-preserve=mode,ownership $SRC_DIR/MaestroPrebuilt/MaestroPrebuilt.apk $TRG_DIR/MaestroPrebuilt/
cp --no-preserve=mode,ownership $SRC_DIR/MyVerizonServices/MyVerizonServices.apk $TRG_DIR/MyVerizonServices/
cp --no-preserve=mode,ownership $SRC_DIR/OBDM_Permissions/OBDM_Permissions.apk $TRG_DIR/OBDM_Permissions/
cp --no-preserve=mode,ownership $SRC_DIR/obdm_stub/obdm_stub.apk $TRG_DIR/obdm_stub/
cp --no-preserve=mode,ownership $SRC_DIR/OemDmTrigger/OemDmTrigger.apk $TRG_DIR/OemDmTrigger/
cp --no-preserve=mode,ownership $SRC_DIR/OsloFeedback/OsloFeedback.apk $TRG_DIR/OsloFeedback/
cp --no-preserve=mode,ownership $SRC_DIR/qcrilmsgtunnel/qcrilmsgtunnel.apk $TRG_DIR/qcrilmsgtunnel/
cp --no-preserve=mode,ownership $SRC_DIR/RefreshRateControl/RefreshRateControl.apk $TRG_DIR/RefreshRateControl/
cp --no-preserve=mode,ownership $SRC_DIR/RilConfigService/RilConfigService.apk $TRG_DIR/RilConfigService/
cp --no-preserve=mode,ownership $SRC_DIR/SafetyHubPrebuilt/SafetyHubPrebuilt.apk $TRG_DIR/SafetyHubPrebuilt/
cp --no-preserve=mode,ownership $SRC_DIR/SCONE/SCONE.apk $TRG_DIR/SCONE/
cp --no-preserve=mode,ownership $SRC_DIR/ScribePrebuilt/ScribePrebuilt.apk $TRG_DIR/ScribePrebuilt/
cp --no-preserve=mode,ownership $SRC_DIR/Showcase/Showcase.apk $TRG_DIR/Showcase/
cp --no-preserve=mode,ownership $SRC_DIR/SprintDM/SprintDM.apk $TRG_DIR/SprintDM/
cp --no-preserve=mode,ownership $SRC_DIR/SprintHM/SprintHM.apk $TRG_DIR/SprintHM/
cp --no-preserve=mode,ownership $SRC_DIR/TetheringEntitlement/TetheringEntitlement.apk $TRG_DIR/TetheringEntitlement/
cp --no-preserve=mode,ownership $SRC_DIR/TmobileGrsuPrebuilt/TmobileGrsuPrebuilt.apk $TRG_DIR/TmobileGrsuPrebuilt/
cp --no-preserve=mode,ownership $SRC_DIR/USCCDM/USCCDM.apk $TRG_DIR/USCCDM/
cp --no-preserve=mode,ownership $SRC_DIR/VzwOmaTrigger/VzwOmaTrigger.apk $TRG_DIR/VzwOmaTrigger/
cp --no-preserve=mode,ownership $SRC_DIR/WfcActivation/WfcActivation.apk $TRG_DIR/WfcActivation/

cp --no-preserve=mode,ownership $SRC_DIR/EuiccGoogle/esim-a1.img $TRG_DIR/EuiccGoogle/
cp --no-preserve=mode,ownership $SRC_DIR/EuiccGoogle/esim-a2.img $TRG_DIR/EuiccGoogle/
cp --no-preserve=mode,ownership $SRC_DIR/EuiccSupportPixel/esim-full-v1.img $TRG_DIR/EuiccSupportPixel/
cp --no-preserve=mode,ownership $SRC_DIR/MyVerizonServices/lib/arm64/libakuaf.so $TRG_DIR/MyVerizonServices/lib/arm64/
cp --no-preserve=mode,ownership $SRC_DIR/MyVerizonServices/lib/arm64/libmotricity.so $TRG_DIR/MyVerizonServices/lib/arm64/
cp --no-preserve=mode,ownership $SRC_DIR/SCONE/lib/arm64/libborders_scone_leveldb_jni.so $TRG_DIR/SCONE/lib/arm64/

SRC_DIR=/media/product/lib
TRG_DIR=/data/android_vendor_google/flame/proprietary/product/priv-app/DMService/lib/arm
cp --no-preserve=mode,ownership $SRC_DIR/libdmengine.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libdmjavaplugin.so $TRG_DIR/

SRC_DIR=/media/product/lib64
TRG_DIR=/data/android_vendor_google/flame/proprietary/product/priv-app/ims/lib/arm64
cp --no-preserve=mode,ownership $SRC_DIR/libimscamera_jni.so $TRG_DIR/
cp --no-preserve=mode,ownership $SRC_DIR/libimsmedia_jni.so $TRG_DIR/
