#!/bin/bash

echo -e "\n\n**** Copying proprietary app ****"
APP_SRC=/media/vendor/app
APP_DST=$PWD/flame/proprietary/app
cp -v --no-preserve=mode,ownership $APP_SRC/CACertService/CACertService.apk $APP_DST/CACertService/
cp -v --no-preserve=mode,ownership $APP_SRC/CneApp/CneApp.apk $APP_DST/CneApp/
cp -v --no-preserve=mode,ownership $APP_SRC/IWlanService/IWlanService.apk $APP_DST/IWlanService/

echo -e "\n\n**** Copying proprietary binaries ****"
BIN_SRC=/media/_/system/bin/
BIN_DST=$PWD/flame/proprietary/bin
cp -v --no-preserve=mode,ownership $BIN_SRC/iw $BIN_DST/
cp -v --no-preserve=mode,ownership $BIN_SRC/move_time_data.sh $BIN_DST/

echo -e "\n\n**** Copying proprietary configs ****"
PERM_SRC=/media/_/system/etc/permissions
PERM_DST=$PWD/flame/proprietary/etc/permissions
cp -v --no-preserve=mode,ownership $PERM_SRC/com.qti.snapdragon.sdk.display.xml $PERM_DST/
cp -v --no-preserve=mode,ownership $PERM_SRC/privapp-permissions-google.xml $PERM_DST/
cp -v --no-preserve=mode,ownership $PERM_SRC/privapp-permissions-platform.xml $PERM_DST/

echo -e "\n\n**** Copying proprietary framwork ****"
FW_SRC=/media/_/system/framework
FW_DST=$PWD/flame/proprietary/framework
cp -v --no-preserve=mode,ownership $FW_SRC/com.qti.snapdragon.sdk.display.jar $FW_DST/
cp -v --no-preserve=mode,ownership $FW_SRC/com.qualcomm.qti.uceservice-V2.0-java.jar $FW_DST/
cp -v --no-preserve=mode,ownership $FW_SRC/vendor.qti.hardware.alarm-V1.0-java.jar $FW_DST/
cp -v --no-preserve=mode,ownership $FW_SRC/vendor.qti.hardware.data.latency-V1.0-java.jar $FW_DST/
cp -v --no-preserve=mode,ownership $FW_SRC/vendor.qti.hardware.factory-V1.0-java.jar $FW_DST/
cp -v --no-preserve=mode,ownership $FW_SRC/vendor.qti.ims.callinfo-V1.0-java.jar $FW_DST/
cp -v --no-preserve=mode,ownership $FW_SRC/vendor.qti.voiceprint-V1.0-java.jar $FW_DST/

echo -e "\n\n**** Copying proprietary libraries (32-bit) ****"
LIB_SRC=/media/_/system/lib
LIB_SRC_2=/media/vendor/lib
LIB_DST=$PWD/flame/proprietary/lib
cp -v --no-preserve=mode,ownership $LIB_SRC/android.hardware.radio@1.3.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/android.hardware.radio@1.4.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/com.qualcomm.qti.bluetooth_audio@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/com.qualcomm.qti.imscmservice@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/com.qualcomm.qti.uceservice@2.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libadsprpc_system.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libcdsprpc_system.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libdiag_system.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libdisplayconfig.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/liblogwrap.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libmdsprpc_system.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libminui.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libmmosal.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libnl.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libOpenCL_system.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libprotobuf-cpp-full.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libqmi_cci_system.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libsdsprpc_system.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libvr_amb_engine.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libvraudio_client.qti.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libvraudio.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libvr_object_engine.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/libvr_sam_wrapper.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.1.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.2.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.3.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.4.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.5.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.6.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.7.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.config@1.8.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.display.postproc@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.alarm@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.data.latency@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.factory@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.iop@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.iop@2.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.perf@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.qteeconnector@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.am@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.ims@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.ims@1.1.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.ims@1.2.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.ims@1.3.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.ims@1.4.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.qcrilhook@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.qtiradio@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.qtiradio@2.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.uim@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.uim@1.1.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.uim_remote_client@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.radio.uim_remote_server@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.seccam@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.hardware.tui_comm@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC/vendor.qti.ims.callinfo@1.0.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libcacertclient.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libdiag.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libdsutils.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libidl.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libjnihelper.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libmdmdetect.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libqmi_cci.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libqmi_client_qmux.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libqmi_encdec.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/libqmiservices.so $LIB_DST/
cp -v --no-preserve=mode,ownership $LIB_SRC_2/vendor.qti.hardware.cacert@1.0.so $LIB_DST/

echo -e "\n\n**** Copying proprietary libraries (64-bit) ****"
LIB64_SRC=/media/_/system/lib64
LIB64_SRC_2=/media/vendor/lib64
LIB64_DST=$PWD/flame/proprietary/lib64
cp -v --no-preserve=mode,ownership $LIB64_SRC/android.hardware.radio@1.3.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/android.hardware.radio@1.4.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/com.qualcomm.qti.bluetooth_audio@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/com.qualcomm.qti.imscmservice@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/com.qualcomm.qti.uceservice@2.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libadsprpc_system.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libcdsprpc_system.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libdiag_system.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libdisplayconfig.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libmdsprpc_system.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libminui.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libmmosal.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libnl.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libOpenCL_system.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libprotobuf-cpp-full.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libqmi_cci_system.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libsdsprpc_system.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libvr_amb_engine.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libvraudio_client.qti.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libvraudio.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libvr_object_engine.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/libvr_sam_wrapper.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.color@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.1.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.2.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.3.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.4.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.5.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.6.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.7.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.config@1.8.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.display.postproc@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.alarm@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.data.latency@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.factory@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.iop@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.iop@2.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.perf@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.qteeconnector@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.am@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.ims@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.ims@1.1.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.ims@1.2.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.ims@1.3.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.ims@1.4.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.qcrilhook@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.qtiradio@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.qtiradio@2.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.uim@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.uim@1.1.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.uim_remote_client@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.radio.uim_remote_server@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.seccam@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.hardware.tui_comm@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC/vendor.qti.ims.callinfo@1.0.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libcacertclient.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libdiag.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libdsutils.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libidl.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libjnihelper.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libmdmdetect.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libqmi_cci.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libqmi_client_qmux.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libqmi_encdec.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/libqmiservices.so $LIB64_DST/
cp -v --no-preserve=mode,ownership $LIB64_SRC_2/vendor.qti.hardware.cacert@1.0.so $LIB64_DST/

echo -e "\n\n**** Copying proprietary product apps ****"
PAPP_SRC=/media/product/app
PAPP_DST=$PWD/flame/proprietary/product/app
cp -v --no-preserve=mode,ownership $PAPP_SRC/atfwd/atfwd.apk $PAPP_DST/atfwd/
cp -v --no-preserve=mode,ownership $PAPP_SRC/colorservice/colorservice.apk $PAPP_DST/colorservice/
cp -v --no-preserve=mode,ownership $PAPP_SRC/com.qualcomm.qti.services.secureui/com.qualcomm.qti.services.secureui.apk $PAPP_DST/com.qualcomm.qti.services.secureui/
cp -v --no-preserve=mode,ownership $PAPP_SRC/datastatusnotification/datastatusnotification.apk $PAPP_DST/datastatusnotification/
cp -v --no-preserve=mode,ownership $PAPP_SRC/MotionSenseBridgePrebuilt/MotionSenseBridgePrebuilt.apk $PAPP_DST/MotionSenseBridgePrebuilt/
cp -v --no-preserve=mode,ownership $PAPP_SRC/QdcmFF/QdcmFF.apk $PAPP_DST/QdcmFF/
cp -v --no-preserve=mode,ownership $PAPP_SRC/QtiTelephonyService/QtiTelephonyService.apk $PAPP_DST/QtiTelephonyService/
cp -v --no-preserve=mode,ownership $PAPP_SRC/SSRestartDetector/SSRestartDetector.apk $PAPP_DST/SSRestartDetector/
cp -v --no-preserve=mode,ownership $PAPP_SRC/Tycho/Tycho.apk $PAPP_DST/Tycho/
cp -v --no-preserve=mode,ownership $PAPP_SRC/uceShimService/uceShimService.apk $PAPP_DST/uceShimService/
cp -v --no-preserve=mode,ownership $PAPP_SRC/uimremoteclient/uimremoteclient.apk $PAPP_DST/uimremoteclient/
cp -v --no-preserve=mode,ownership $PAPP_SRC/uimremoteserver/uimremoteserver.apk $PAPP_DST/uimremoteserver/
cp -v --no-preserve=mode,ownership $PAPP_SRC/VZWAPNLib/VZWAPNLib.apk $PAPP_DST/VZWAPNLib/

echo -e "\n\n**** Copying proprietary product configs ****"
PETC_SRC=/media/product/etc
PETC_DST=$PWD/flame/proprietary/product/etc
cp -v --no-preserve=mode,ownership $PETC_SRC/ambient/matcher_tah.leveldb $PETC_DST/ambient/
cp -v --no-preserve=mode,ownership $PETC_SRC/CarrierSettings/* $PETC_DST/CarrierSettings/
cp -v --no-preserve=mode,ownership $PETC_SRC/felica/common.cfg $PETC_DST/felica/
cp -v --no-preserve=mode,ownership $PETC_SRC/felica/mfm.cfg $PETC_DST/felica/
cp -v --no-preserve=mode,ownership $PETC_SRC/felica/mfs.cfg $PETC_DST/felica/
cp -v --no-preserve=mode,ownership $PETC_SRC/firmware/music_detector.descriptor $PETC_DST/firmware/
cp -v --no-preserve=mode,ownership $PETC_SRC/firmware/music_detector.sound_model $PETC_DST/firmware/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/android.hardware.telephony.euicc.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.android.omadm.service.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.android.sdm.plugins.connmo.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.android.sdm.plugins.dcmo.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.android.sdm.plugins.diagmon.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.android.sdm.plugins.sprintdm.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.android.sdm.plugins.usccdm.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.android.vzwomatrigger.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.customermobile.preload.vzw.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.google.android.apps.dreamliner.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.google.android.hardwareinfo.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.google.omadm.trigger.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.qualcomm.qcrilmsgtunnel.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.verizon.apn.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.verizon.llkagent.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/com.verizon.services.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/features-verizon.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/obdm_permissions.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/org_codeaurora_ims.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/privapp-permissions-google-ps.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/privapp-permissions-google-p.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/qcrilhook.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/split-permissions-google.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/telephonyservice.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/tmo_grsu_permissions.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/uimremoteclient.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/uimremoteserver.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/UimService.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/permissions/vzw_mvs_permissions.xml $PETC_DST/permissions/
cp -v --no-preserve=mode,ownership $PETC_SRC/res/images/charger/battery_fail.png $PETC_DST/res/images/charger/
cp -v --no-preserve=mode,ownership $PETC_SRC/res/images/charger/battery_scale.png $PETC_DST/res/images/charger/
cp -v --no-preserve=mode,ownership $PETC_SRC/res/images/charger/main_font.png $PETC_DST/res/images/charger/
cp -v --no-preserve=mode,ownership $PETC_SRC/res/values/charger/animation.txt $PETC_DST/res/values/charger/
cp -v --no-preserve=mode,ownership $PETC_SRC/sysconfig/dreamliner.xml $PETC_DST/sysconfig/
cp -v --no-preserve=mode,ownership $PETC_SRC/sysconfig/nga.xml $PETC_DST/sysconfig/
cp -v --no-preserve=mode,ownership $PETC_SRC/sysconfig/pixel_2019_exclusive.xml $PETC_DST/sysconfig/
cp -v --no-preserve=mode,ownership $PETC_SRC/sysconfig/pixel_experience_2019_midyear.xml $PETC_DST/sysconfig/
cp -v --no-preserve=mode,ownership $PETC_SRC/sysconfig/pixel_experience_2019.xml $PETC_DST/sysconfig/
cp -v --no-preserve=mode,ownership $PETC_SRC/sysconfig/tmo_grsu_sysconfig.xml $PETC_DST/sysconfig/
cp -v --no-preserve=mode,ownership $PETC_SRC/sysconfig/whitelist_com.android.omadm.service.xml $PETC_DST/sysconfig/
cp -v --no-preserve=mode,ownership $PETC_SRC/vintf/manifest/vendor.qti.hardware.radio.atcmdfwd@1.0.xml $PETC_DST/vintf/manifest/

echo -e "\n\n**** Fixing errors in proprietary product configs ****"
sed -i 's/version="2.0"/version="1.0"/' $PETC_DST/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml
sed -i 's/\/system\/product/\/product/' $PETC_DST/permissions/telephonyservice.xml

echo -e "\n\n**** Copying proprietary product framwork ****"
PFW_SRC=/media/product/framework
PFW_DST=$PWD/flame/proprietary/product/framework
cp -v --no-preserve=mode,ownership $PFW_SRC/com.qualcomm.qti.imscmservice-V2.0-java.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/com.qualcomm.qti.imscmservice-V2.1-java.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/com.qualcomm.qti.imscmservice-V2.2-java.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/com.qualcomm.qti.uceservice-V2.1-java.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/libhwinfo.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/qcrilhook.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/QtiTelephonyServicelibrary.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/uimremoteclientlibrary.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/uimremoteserverlibrary.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/vendor.qti.hardware.data.connection-V1.0-java.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/vendor.qti.hardware.data.dynamicdds-V1.0-java.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/vendor.qti.hardware.data.iwlan-V1.0-java.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/vendor.qti.ims.rcsconfig-V1.0-java.jar $PFW_DST/
cp -v --no-preserve=mode,ownership $PFW_SRC/vendor.qti.latency-V2.0-java.jar $PFW_DST/

echo -e "\n\n**** Copying proprietary product libraries (32-bit) ****"
PLIB_SRC=/media/product/lib
PLIB_DST=$PWD/flame/proprietary/product/lib
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.qualcomm.qti.ant@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.qualcomm.qti.imscmservice@2.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.qualcomm.qti.imscmservice@2.1.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.qualcomm.qti.imscmservice@2.2.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.qualcomm.qti.uceservice@2.1.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.quicinc.cne.api@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.quicinc.cne.api@1.1.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.quicinc.cne.constants@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.quicinc.cne.constants@2.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/com.quicinc.cne.constants@2.1.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/libdmengine.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/libdmjavaplugin.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/libimscamera_jni.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/libimsmedia_jni.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/lib-imsvideocodec.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/lib-imsvtextutils.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/lib-imsvt.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/lib-imsvtutils.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/libsdm-disp-apis.qti.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/libsd_sdk_display.qti.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/libsecureuisvc_jni.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/libsecureui_svcsock_system.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.google.wifi_ext@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.google.wireless_charger@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.google.wireless_charger@1.1.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.data.factory@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.hardware.data.connection@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.hardware.data.dynamicdds@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.hardware.data.iwlan@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.hardware.perf@2.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.hardware.radio.qtiradio@2.1.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.hardware.radio.qtiradio@2.2.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.hardware.radio.uim_remote_client@1.1.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.ims.rcsconfig@1.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.imsrtpservice@2.0.so $PLIB_DST/
cp -v --no-preserve=mode,ownership $PLIB_SRC/vendor.qti.latency@2.0.so $PLIB_DST/

echo -e "\n\n**** Copying proprietary product libraries (64-bit) ****"
PLIB64_SRC=/media/product/lib64
PLIB64_DST=$PWD/flame/proprietary/product/lib64
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.qualcomm.qti.ant@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.qualcomm.qti.imscmservice@2.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.qualcomm.qti.imscmservice@2.1.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.qualcomm.qti.imscmservice@2.2.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.qualcomm.qti.uceservice@2.1.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.quicinc.cne.api@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.quicinc.cne.api@1.1.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.quicinc.cne.constants@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.quicinc.cne.constants@2.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/com.quicinc.cne.constants@2.1.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libaptX_encoder.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libaptXHD_encoder.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libgdx.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libimscamera_jni.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libimsmedia_jni.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/lib-imsvideocodec.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/lib-imsvtextutils.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/lib-imsvt.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/lib-imsvtutils.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libsdm-disp-apis.qti.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libsd_sdk_display.qti.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libsecureuisvc_jni.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/libsecureui_svcsock_system.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.google.wifi_ext@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.google.wireless_charger@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.google.wireless_charger@1.1.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.data.factory@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.hardware.data.connection@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.hardware.data.dynamicdds@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.hardware.data.iwlan@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.hardware.perf@2.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.hardware.radio.qtiradio@2.1.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.hardware.radio.qtiradio@2.2.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.hardware.radio.uim_remote_client@1.1.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.ims.rcsconfig@1.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.imsrtpservice@2.0.so $PLIB64_DST/
cp -v --no-preserve=mode,ownership $PLIB64_SRC/vendor.qti.latency@2.0.so $PLIB64_DST/

echo -e "\n\n**** Copying proprietary product privileged apps ****"
PPAPP_SRC=/media/product/priv-app
PPAPP_TRG=$PWD/flame/proprietary/product/priv-app
cp -v --no-preserve=mode,ownership $PPAPP_SRC/AmbientSensePrebuilt/AmbientSensePrebuilt.apk $PPAPP_TRG/AmbientSensePrebuilt/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/AppDirectedSMSService/AppDirectedSMSService.apk $PPAPP_TRG/AppDirectedSMSService/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/CarrierLocation/CarrierLocation.apk $PPAPP_TRG/CarrierLocation/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/CarrierServices/CarrierServices.apk $PPAPP_TRG/CarrierServices/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/CarrierSettings/CarrierSettings.apk $PPAPP_TRG/CarrierSettings/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/CarrierSetup/CarrierSetup.apk $PPAPP_TRG/CarrierSetup/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/CarrierWifi/CarrierWifi.apk $PPAPP_TRG/CarrierWifi/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/ConnMO/ConnMO.apk $PPAPP_TRG/ConnMO/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/DCMO/DCMO.apk $PPAPP_TRG/DCMO/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/DiagMon/DiagMon.apk $PPAPP_TRG/DiagMon/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/DMService/DMService.apk $PPAPP_TRG/DMService/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/DreamlinerPrebuilt/DreamlinerPrebuilt.apk $PPAPP_TRG/DreamlinerPrebuilt/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/DreamlinerUpdater/DreamlinerUpdater.apk $PPAPP_TRG/DreamlinerUpdater/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/EuiccGoogle/EuiccGoogle.apk $PPAPP_TRG/EuiccGoogle/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/EuiccSupportPixel/EuiccSupportPixel.apk $PPAPP_TRG/EuiccSupportPixel/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/GCS/GCS.apk $PPAPP_TRG/GCS/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/grilservice/grilservice.apk $PPAPP_TRG/grilservice/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/HardwareInfo/HardwareInfo.apk $PPAPP_TRG/HardwareInfo/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/HotwordEnrollmentOKGoogleHEMIDELTA/HotwordEnrollmentOKGoogleHEMIDELTA.apk $PPAPP_TRG/HotwordEnrollmentOKGoogleHEMIDELTA/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/HotwordEnrollmentXGoogleHEMIDELTA/HotwordEnrollmentXGoogleHEMIDELTA.apk $PPAPP_TRG/HotwordEnrollmentXGoogleHEMIDELTA/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/ims/ims.apk $PPAPP_TRG/ims/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/LLKAgent/LLKAgent.apk $PPAPP_TRG/LLKAgent/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/MyVerizonServices/MyVerizonServices.apk $PPAPP_TRG/MyVerizonServices/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/OBDM_Permissions/OBDM_Permissions.apk $PPAPP_TRG/OBDM_Permissions/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/obdm_stub/obdm_stub.apk $PPAPP_TRG/obdm_stub/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/OemDmTrigger/OemDmTrigger.apk $PPAPP_TRG/OemDmTrigger/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/OsloFeedback/OsloFeedback.apk $PPAPP_TRG/OsloFeedback/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/qcrilmsgtunnel/qcrilmsgtunnel.apk $PPAPP_TRG/qcrilmsgtunnel/
#cp -v --no-preserve=mode,ownership $PPAPP_SRC/RefreshRateControl/RefreshRateControl.apk $PPAPP_TRG/RefreshRateControl/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/RilConfigService/RilConfigService.apk $PPAPP_TRG/RilConfigService/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/SCONE/SCONE.apk $PPAPP_TRG/SCONE/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/Showcase/Showcase.apk $PPAPP_TRG/Showcase/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/SprintDM/SprintDM.apk $PPAPP_TRG/SprintDM/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/SprintHM/SprintHM.apk $PPAPP_TRG/SprintHM/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/TetheringEntitlement/TetheringEntitlement.apk $PPAPP_TRG/TetheringEntitlement/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/TmobileGrsuPrebuilt/TmobileGrsuPrebuilt.apk $PPAPP_TRG/TmobileGrsuPrebuilt/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/USCCDM/USCCDM.apk $PPAPP_TRG/USCCDM/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/VzwOmaTrigger/VzwOmaTrigger.apk $PPAPP_TRG/VzwOmaTrigger/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/WfcActivation/WfcActivation.apk $PPAPP_TRG/WfcActivation/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/EuiccGoogle/esim-a1.img $PPAPP_TRG/EuiccGoogle/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/EuiccGoogle/esim-a2.img $PPAPP_TRG/EuiccGoogle/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/EuiccSupportPixel/esim-full-v1.img $PPAPP_TRG/EuiccSupportPixel/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/MyVerizonServices/lib/arm64/libakuaf.so $PPAPP_TRG/MyVerizonServices/lib/arm64/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/MyVerizonServices/lib/arm64/libmotricity.so $PPAPP_TRG/MyVerizonServices/lib/arm64/
cp -v --no-preserve=mode,ownership $PPAPP_SRC/SCONE/lib/arm64/libborders_scone_leveldb_jni.so $PPAPP_TRG/SCONE/lib/arm64/
